version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  request-monkey:
    lang: dockerfile
    handler: ./
    image: request-monkey:latest
    environment:
      exec_timeout: 1020
      write_timeout: 1000
      read_timeout: 1000
      combine_output: false
    labels:
      com.openfaas.scale.zero: true

