version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  request-monkey:
    lang: python-geospatial
    handler: ./function
    image: request-monkey:0.0.1
    environment:
      exec_timeout: 60
      write_timeout: 70
      read_timeout: 70
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
