version: 1.0
provider:
  name: openfaas
  gateway: https://faas.srv3.disarm.io
functions:
  request-monkey:
    lang: python3
    handler: ./function
    image: locational/request-monkey:0.0.3
    environment:
      exec_timeout: 60
      write_timeout: 70
      read_timeout: 70
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
